# Generated by Django 5.0.6 on 2024-05-20 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=1000)),
                (
                    "language",
                    models.IntegerField(
                        choices=[
                            (0, "Русский"),
                            (1, "English"),
                            (2, "Deutsch"),
                            (3, "Francias"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "speech_full",
                    models.IntegerField(
                        choices=[
                            (0, "Speech only first trigger"),
                            (1, "Speech all triggers"),
                        ]
                    ),
                ),
                (
                    "success_messages",
                    models.CharField(
                        help_text="Bot success messages, should be splitten with comma",
                        max_length=500,
                    ),
                ),
                (
                    "failure_messages",
                    models.CharField(
                        help_text="Bot failure messages, should be splitten with comma",
                        max_length=500,
                    ),
                ),
                (
                    "repeat_commands",
                    models.IntegerField(
                        choices=[
                            (0, "Don't repeat all commands on failure"),
                            (1, "Repeat all commands on failure"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "redirect_url",
                    models.CharField(
                        help_text="Link or name of the page on the site to be redirected to. For an external page — it must start with 'www', otherwise the link will be recognized as the template name.",
                        max_length=150,
                    ),
                ),
                (
                    "trigger_words",
                    models.CharField(
                        default="",
                        help_text="Code words for executing the command. Sets of code words must be separated by a comma, and code words in the set must be separated by a space.",
                        max_length=1000,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom message that will be displayed when the command is executed. Leave empty for the default option",
                        max_length=500,
                    ),
                ),
                (
                    "api_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API URL to update message",
                        max_length=150,
                    ),
                ),
                (
                    "api_flag",
                    models.IntegerField(
                        choices=[
                            (0, "Message will be set default"),
                            (1, "Message will be updated using API URL"),
                        ],
                        default=0,
                        help_text="Flag that will handle message",
                    ),
                ),
                (
                    "api_header",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="API header, that will be used to extract data",
                        max_length=200,
                    ),
                ),
                (
                    "requests_headers",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="request headers,should be written as json",
                        max_length=500,
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        help_text="bot that will execute the command",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equitech.bot",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
